### ISSUE TITLE
3.0.6 upgrade issue

### ISSUE THREAD

**Issue by alankky2010** [monim67/django-bootstrap-datepicker-plus#67]
Traceback (most recent call last):
  File "C:\Users\alank\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\alank\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\alank\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\alank\Documents\Python\crm1\accounts\decorators.py", line 20, in wrapper_func
    return view_func(request, *args, **kwargs)
  File "C:\Users\alank\Documents\Python\crm1\accounts\views.py", line 677, in customer
    orders = myFilter.qs
  File "C:\Users\alank\AppData\Local\Programs\Python\Python39\lib\site-packages\django_filters\filterset.py", line 242, in qs
    self.errors
  File "C:\Users\alank\AppData\Local\Programs\Python\Python39\lib\site-packages\django_filters\filterset.py", line 219, in errors
    return self.form.errors
  File "C:\Users\alank\AppData\Local\Programs\Python\Python39\lib\site-packages\django\forms\forms.py", line 170, in errors
    self.full_clean()
  File "C:\Users\alank\AppData\Local\Programs\Python\Python39\lib\site-packages\django\forms\forms.py", line 372, in full_clean
    self._clean_fields()
  File "C:\Users\alank\AppData\Local\Programs\Python\Python39\lib\site-packages\django\forms\forms.py", line 384, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
**AttributeError: 'DateTimePickerInput' object has no attribute 'value_from_datadict'**

When I rolled back to 3.0.5, no such issue arises.  Any hint to resolve this issue?  Thanks.

**Comment by monim67** [comment]
Cannot reproduce your issue, which version of `django` are you using?

**Comment by alankky2010** [comment]
Hi monim67, I am using the latest version - 3.2.9. Also, I am using 

1. django-bootstrap4 v21.1 [https://django-bootstrap4.readthedocs.io/en/latest/index.html](url)
2. django-filter v.21.1 [https://github.com/carltongibson/django-filter/tree/main](url)
3. python v.3.9.5
4. postgreSQL v.13

**Comment by monim67** [comment]
3.0.6 has been yanked from pypi.
