### ISSUE TITLE
Unable to open time picker from datetime picker in bootstrap

### ISSUE THREAD

**Issue by anlx-sw** [monim67/django-bootstrap-datepicker-plus#93]
**Describe the bug**
I am unable to get the time picker to open from the datetime picker in a form. My issue is quite simmiluar to #92 .

When I click the "Select Time" button I can see the time menu expand downward until it is full size then it disappears. The icon then switches to the calendar icon instead of the clock and nothing else changes. All of the media files are being loaded, all other functionality appears to work. If I add the "sideBySide" option to the widget I can use both - and i will stick to this solution.

I don't use any modals - just regular django forms with crispy and htmx with a project based on django-cookiecutter.
I tried placing the "form media" in several places (base.html, directly above div containting form, directly within form tags etc.) I don't see any errors in script console.  

I will stick to the "sideBySide" configuration - so this issue can be also directly closed from my point of view.  but as I found a recent other issue concerning a simmilar problem i wanted to inform you.

**Comment by monim67** [comment]
Thanks for filing this issue, it is always huge help for others trying ti use this widget. Unfortunately I can't reproduce this issue anyways. Any help to reproduce the issue would be highly appreciated.

**Comment by anikwai** [comment]
I experienced the same issue when using jquery and mdb. In the browser console it says "caught TypeError: Cannot read properties of null (reading 'hasAttribute')
    at i (index.js:181:32)
    at Module.n (event-handler.js:16:11)
    at o (bootstrap:19:22)
    at bootstrap:83:10
    at universalModuleDefinition:9:17
    at universalModuleDefinition:10:2"
